### ISSUE TITLE
How to build deb pkgs?

### ISSUE THREAD

**Issue by hgfischer** [lamby/pkg-redis#10]
Hello,

I've found this repo through http://archive.ubuntu.com/ubuntu/pool/universe/r/redis/redis_3.2.1-1.dsc and I wanted to build the latest 3.2.6 for xenial and upload it in my own PPA.

Could you guys give me the general instructions on how to do it? I took a look in this repo and didn't found any docs about it.

best

**Comment by lamby** [comment]
I would look at the documentation for the (more generic) git-buildpackage documentation - any docs here would simply be a duplication of that. :)  Good luck!
