### ISSUE TITLE
Why redis-sentinel depends on redis-server?

### ISSUE THREAD

**Issue by koleo** [lamby/pkg-redis#13]
I was looking to install a redis-sentinel instance without redis-server using apt repository (debian stretch backport), but I realize that redis-sentinel depends on redis-server. Is there a good reason for this dependence?

Can redis-sentinel not work without a redis-server running on the same server?

**Comment by lamby** [comment]
Good question; I don't think there is a reason. Please could you file this against the package in Debian by sending the following email:

```
To: submit@bugs.debian.org
Subject: redis-sentinel: Please remove dependency on redis-server

Package: redis-sentinel
Version: 5:4.0.6-1
Severity: wishlist

Please remove the dependency on redis-server. [Any other description here]
```

Thanks!

**Comment by koleo** [comment]
Done (using reportbug utility). Thank you!

**Comment by lamby** [comment]
> using reportbug utility

Haha! ♥
